name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying application..."
      - run: echo "Deployment complete!"
